### ISSUE TITLE
Error: Cannot find module 'graphql'

### ISSUE THREAD

**Issue by ohenepee** [sifrr/sifrr#216]
I have no need for GraphQL... can u make this optional?

Error occuring when using `@sifrr/server`

**Comment by aadityataparia** [comment]
Made optional now, but haven't released yet! You can use v0.0.5, if you don't need features added in v0.0.6

**Comment by ohenepee** [comment]
Use added support for uWebSocket.js 15.11.0 in 6.0.0

Do you have an ETA on the next release?

**Comment by aadityataparia** [comment]
No ETA yet, sorry. A bit busy, so haven't had much time for sifrr lately.
