### ISSUE TITLE
Adding Headers To Static Serving

### ISSUE THREAD

**Issue by ohenepee** [sifrr/sifrr#217]
How to you add custom headers to static server?

**Comment by aaditya-taparia** [comment]
https://sifrr.github.io/sifrr/#/./packages/server/sifrr-server/?id=sendfile static server options are same as `sendFile` with some extra options.

**Comment by aadityataparia** [comment]
https://sifrr.github.io/sifrr/#/./packages/server/sifrr-server/?id=sendfile static server options are same as `sendFile` with some extra options.
