### ISSUE TITLE
Headers duplicated if server under high-load

### ISSUE THREAD

**Issue by dalisoft** [sifrr/sifrr#280]
**Describe the bug**
For more information, go [here](https://github.com/dalisoft/nanoexpress/issues/63)

**To Reproduce**
Steps to reproduce the behavior: See [here](https://github.com/dalisoft/nanoexpress/issues/63#issuecomment-564961712)

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

-   OS: macOS
-   Browser: Chrome-only (for me on Safari works fine)
-   Version 79

**Additional context**

It's not a ad of my library, our libraries use same library (uWebSocket.js), so i decided to notify you about this bug. Your library works great and my library works too, our goal may be different, but issue applies to our libraries, let's we together fixing this, but first, maybe we should notify author of uWebSockets.js about this issue?

**Comment by aadityataparia** [comment]
Sure. Let me know how to reproduce it.

**Comment by aadityataparia** [comment]
Saw the link. Let's create issue on uwebsockets.
