### ISSUE TITLE
Update @sifrr/dom "package.json"

### ISSUE THREAD

**Issue by rev1912** [sifrr/sifrr#403]
Err when installing with npm `npm i @sifrr/dom` or yarn `yarn add @sifrr/dom` In `package.json` it require itself as dependency

`"dependencies": {
"@sifrr/dom": "file:./packages/browser/sifrr-dom"
  },
  "peerDependencies": {
    "@sifrr/template": "0.0.6"
  },`

But no `./packages/browser/sifrr-dom` in `sifrr-dom` please remove it or if it require itself please use upper level `../../`
Also. update peer `@sifrr/template` to `^0.0.6 or 0.0.8` too (prevent npm warning!)

Sorry, for my english and/or this is not issue but i really got error

**Comment by rev1912** [comment]
Closed it already added, waiting for rollup build

**Comment by aadityataparia** [comment]
@rev1912 this should be fixed in v0.0.9
